### ISSUE TITLE
colour choices

### ISSUE THREAD

**Issue by bijang** [MurzNN/TST-Colored-tabs#11]
It's a great idea, is there a logic to the colour choices though, or is it just random colour selection and if that's the case is it from a predefined number of swatches or just a colour map?

**Comment by lotsoffood** [comment]
Great idea, but would love to be able to change the color choices here as everything is heavy pastel.

**Comment by MurzNN** [comment]
Colors are generated via splitting in HSL color mode value of hue's 360 degrees to equal parts (15 by default), this way must generate palette without too near colors. 

Implementing custom color palette will be not so user friendly, because manually select 15+ different colors is not so easy task.

For make colors less pastel, you can play with saturation and lightness values in extension settings. Also in last version I implement custom per-host colors.

**Comment by Solid-Ice8** [comment]
I searched "color tabs" in add-ons and, there was one that has the ability to choose a color, but it wasn't able to 'accept' the color so, maybe it's not so simple.

I noticed majority of the coding has been done with JavaScript on many add-ons like these, perhaps some expertise could help us.

**Comment by MurzNN** [comment]
It's not so hard to implement in code, but hard for user interface (selecting 15+ colors manually), so, I think, this feature will not be used for most of users. I want to make extension simple, so don't plan to implement custom color palette editor.
